import {
  createRecursiveDocument,
  validateRecursiveDocument,
  type Geometry,
  type RecursiveDocument,
} from './recursiveDocument';
import { indexHierarchy } from './recursiveHierarchy';
import { recursiveVisibility } from './recursiveVisibility';
export const stressGeneratorVersion = 1;
export interface StressSettings {
  seed: string;
  roots: number;
  breadth: number;
  depth: number;
  connectionDensity: number;
  textCharacters: number;
  codeLines: number;
  savedLayouts: number;
  depthMode: 'mixed' | 'all' | 'collapsed';
  rootSpacing: number;
}
export const stressPresets: Record<string, Omit<StressSettings, 'seed'>> = {
  small: {
    roots: 3,
    breadth: 2,
    depth: 2,
    connectionDensity: 0.25,
    textCharacters: 80,
    codeLines: 2,
    savedLayouts: 3,
    depthMode: 'mixed',
    rootSpacing: 1200,
  },
  large: {
    roots: 24,
    breadth: 4,
    depth: 3,
    connectionDensity: 0.15,
    textCharacters: 80,
    codeLines: 2,
    savedLayouts: 3,
    depthMode: 'mixed',
    rootSpacing: 1600,
  },
  sparse: {
    roots: 40,
    breadth: 2,
    depth: 2,
    connectionDensity: 0.02,
    textCharacters: 20,
    codeLines: 0,
    savedLayouts: 2,
    depthMode: 'mixed',
    rootSpacing: 3000,
  },
  dense: {
    roots: 4,
    breadth: 6,
    depth: 2,
    connectionDensity: 1,
    textCharacters: 100,
    codeLines: 3,
    savedLayouts: 3,
    depthMode: 'all',
    rootSpacing: 500,
  },
  deep: {
    roots: 2,
    breadth: 1,
    depth: 128,
    connectionDensity: 1,
    textCharacters: 20,
    codeLines: 1,
    savedLayouts: 3,
    depthMode: 'mixed',
    rootSpacing: 1200,
  },
  'reveal-all': {
    roots: 8,
    breadth: 3,
    depth: 3,
    connectionDensity: 0.5,
    textCharacters: 60,
    codeLines: 2,
    savedLayouts: 4,
    depthMode: 'all',
    rootSpacing: 1800,
  },
};
export function normalizeStressSettings(
  input: Partial<StressSettings>,
): StressSettings {
  if (!input || typeof input !== 'object' || Array.isArray(input))
    throw new Error('Settings must be an object.');
  const defaults: StressSettings = {
    ...stressPresets.small,
    seed: 'depthplan-stress-v1',
  };
  if (Object.keys(input).some((key) => !Object.hasOwn(defaults, key)))
    throw new Error('Unknown stress setting.');
  const settings = { ...defaults, ...input };
  if (typeof settings.seed !== 'string' || !settings.seed.length)
    throw new Error('Seed must be a nonempty string.');
  for (const key of [
    'roots',
    'breadth',
    'depth',
    'textCharacters',
    'codeLines',
    'savedLayouts',
    'rootSpacing',
  ] as const)
    if (!Number.isSafeInteger(settings[key]) || settings[key] < 0)
      throw new Error(`${key} must be a nonnegative safe integer.`);
  if (
    !settings.roots ||
    !settings.rootSpacing ||
    !settings.savedLayouts ||
    settings.savedLayouts > settings.depth + 1 ||
    (settings.depth > 0 && !settings.breadth)
  )
    throw new Error(
      'Roots/spacing/layout count must be positive, layouts cannot exceed depth+1, and nonzero depth needs children.',
    );
  if (!['mixed', 'all', 'collapsed'].includes(settings.depthMode))
    throw new Error('Invalid depth mode.');
  if (
    settings.depth > 0 &&
    settings.depthMode !== 'collapsed' &&
    settings.savedLayouts < 2
  )
    throw new Error('Mixed/all depth requires at least two saved layouts.');
  if (
    !Number.isFinite(settings.connectionDensity) ||
    settings.connectionDensity < 0 ||
    settings.connectionDensity > 1
  )
    throw new Error('Connection density must be between 0 and 1.');
  const perRoot =
    settings.breadth === 1
      ? settings.depth + 1
      : (settings.breadth ** (settings.depth + 1) - 1) / (settings.breadth - 1);
  if (!Number.isSafeInteger(perRoot * settings.roots))
    throw new Error(
      'Requested population exceeds exact integer representation.',
    );
  return settings;
}
function seededRandom(seed: string) {
  let state = 2166136261;
  for (const character of seed)
    state = Math.imul(state ^ character.codePointAt(0)!, 16777619) >>> 0;
  state ||= 1;
  return () => {
    state ^= state << 13;
    state ^= state >>> 17;
    state ^= state << 5;
    return (state >>> 0) / 4294967296;
  };
}
/** No clock, UUID, renderer, file I/O or live-document state enters the generated bytes. */
export function generateStressDocument(input: Partial<StressSettings>) {
  const settings = normalizeStressSettings(input),
    random = seededRandom(settings.seed);
  const document: RecursiveDocument = createRecursiveDocument(
    'stress-v1',
    `Stress ${settings.seed}`,
    '2000-01-01T00:00:00.000Z',
  );
  document.extensions = {
    stressGenerator: {
      version: stressGeneratorVersion,
      settings: { ...settings },
    },
  };
  let nextId = 0;
  const pending: Array<{
    parentId: string | null;
    generation: number;
    sibling: number;
  }> = Array.from({ length: settings.roots }, (_, sibling) => ({
    parentId: null,
    generation: 0,
    sibling,
  }));
  const text = 'Diagram < & > reproducible content. '
    .repeat(Math.ceil(settings.textCharacters / 35))
    .slice(0, settings.textCharacters);
  for (let at = 0; at < pending.length; at++) {
    const entry = pending[at],
      id = `object-${String(nextId++).padStart(7, '0')}`;
    const columns = Math.ceil(
      Math.sqrt(entry.parentId === null ? settings.roots : settings.breadth),
    );
    const x =
      entry.parentId === null
        ? (entry.sibling % columns) * settings.rootSpacing
        : ((entry.sibling % columns) - (columns - 1) / 2) * 240;
    const y =
      entry.parentId === null
        ? Math.floor(entry.sibling / columns) * settings.rootSpacing
        : (Math.floor(entry.sibling / columns) - 0.5) * 180;
    const geometry: Geometry = {
      x: x + Math.floor(random() * 9),
      y: y + Math.floor(random() * 9),
      width:
        entry.generation < settings.depth ? Math.max(400, columns * 240) : 180,
      height:
        entry.generation < settings.depth
          ? Math.max(300, Math.ceil(settings.breadth / columns) * 180)
          : 140,
      rotation: 0,
      z: entry.sibling,
    };
    const split = Math.floor(text.length / 2);
    document.objects[id] = {
      id,
      parentId: entry.parentId,
      name: `Node ${id}`,
      type: entry.generation < settings.depth ? 'frame' : 'rectangle',
      geometry,
      content: [
        ...(text
          ? [
              {
                type: 'paragraph' as const,
                runs: [
                  { text: text.slice(0, split), marks: { bold: true } },
                  {
                    text: text.slice(split),
                    marks: { italic: true, color: '#1d4ed8' },
                  },
                ],
              },
            ]
          : []),
        ...(settings.codeLines
          ? [
              {
                type: 'code' as const,
                language: 'typescript' as const,
                wrap: false,
                text: Array.from(
                  { length: settings.codeLines },
                  (_, line) =>
                    `\tconst value${line} = ${Math.floor(random() * 1000)};\r\n`,
                ).join(''),
              },
            ]
          : []),
      ],
      style: { fill: '#ffffff', stroke: '#64748b', strokeWidth: 1.5 },
      ...(entry.generation < settings.depth
        ? { boundaryPoints: { port: { side: 'left' as const, offset: 0.5 } } }
        : {}),
    };
    if (entry.parentId === null) {
      document.rootDepths[id] =
        settings.depthMode === 'all'
          ? settings.depth
          : settings.depthMode === 'collapsed'
            ? 0
            : entry.sibling % (settings.depth + 1);
      document.layouts[id] = {};
    }
    if (entry.generation < settings.depth)
      for (let sibling = 0; sibling < settings.breadth; sibling++)
        pending.push({
          parentId: id,
          generation: entry.generation + 1,
          sibling,
        });
  }
  const hierarchy = indexHierarchy(document.objects);
  for (const root of hierarchy.roots) {
    const depths = new Set([0, document.rootDepths[root]]);
    for (
      let depth = 1;
      depth <= settings.depth && depths.size < settings.savedLayouts;
      depth++
    )
      depths.add(depth);
    for (const depth of depths)
      document.layouts[root][depth] = Object.fromEntries(
        hierarchy.byRoot
          .get(root)!
          .filter((id) => hierarchy.entries.get(id)!.generation <= depth)
          .map((id) => [
            id,
            {
              ...document.objects[id].geometry,
              x: document.objects[id].geometry.x + depth * 3,
              y: document.objects[id].geometry.y + depth * 2,
            },
          ]),
      );
  }
  let candidates = 0,
    routes = 0;
  const add = (
    ownerId: string | null,
    start: RecursiveDocument['connections'][string]['start'],
    end: RecursiveDocument['connections'][string]['end'],
  ) => {
    candidates++;
    // Accumulated density realizes exactly floor(density * candidate count).
    if (
      Math.floor(candidates * settings.connectionDensity) ===
      Math.floor((candidates - 1) * settings.connectionDensity)
    )
      return;
    const id = `route-${String(routes++).padStart(7, '0')}`;
    document.connections[id] = {
      id,
      ownerId,
      kind: 'arrow',
      z: 0,
      start,
      end,
      style: { stroke: '#475569', strokeWidth: 2 },
    };
  };
  const endpoint = (objectId: string) => ({
    kind: 'object' as const,
    objectId,
    side: 'right' as const,
    offset: 0.5,
  });
  for (const [ownerId, children] of hierarchy.children) {
    for (let a = 0; a < children.length; a++)
      for (let b = a + 1; b < children.length; b++)
        add(ownerId, endpoint(children[a]), endpoint(children[b]));
    if (ownerId !== null)
      for (const child of children)
        add(
          ownerId,
          { kind: 'boundary', objectId: ownerId, pointId: 'port' },
          endpoint(child),
        );
  }
  validateRecursiveDocument(document);
  const { visible } = recursiveVisibility(document);
  return {
    document,
    settings,
    counts: {
      objects: nextId,
      roots: hierarchy.roots.length,
      maximumDepth: settings.depth,
      visible: visible.size,
      hidden: nextId - visible.size,
      connections: Object.keys(document.connections).length,
      connectionCandidates: candidates,
      boundaryPoints: Object.values(document.objects).filter(
        (o) => o.boundaryPoints,
      ).length,
      savedLayouts: Object.values(document.layouts).reduce(
        (n, layouts) => n + Object.keys(layouts).length,
        0,
      ),
      textCharacters: nextId * settings.textCharacters,
      codeLines: nextId * settings.codeLines,
    },
  };
}
